# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(53, 53, 53);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.boton1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton1.setGeometry(QtCore.QRect(50, 90, 121, 23))
        self.boton1.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.boton1.setObjectName("boton1")
        self.boton2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton2.setGeometry(QtCore.QRect(180, 90, 121, 23))
        self.boton2.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.boton2.setObjectName("boton2")
        self.result = QtWidgets.QTextEdit(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(50, 240, 621, 291))
        self.result.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.result.setObjectName("result")
        self.combox = QtWidgets.QComboBox(self.centralwidget)
        self.combox.setGeometry(QtCore.QRect(50, 50, 211, 22))
        self.combox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.combox.setObjectName("combox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 111, 21))
        self.label.setObjectName("label")
        self.comboy = QtWidgets.QComboBox(self.centralwidget)
        self.comboy.setGeometry(QtCore.QRect(370, 50, 211, 22))
        self.comboy.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboy.setObjectName("comboy")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 20, 111, 21))
        self.label_2.setObjectName("label_2")
        self.comboes = QtWidgets.QComboBox(self.centralwidget)
        self.comboes.setGeometry(QtCore.QRect(50, 160, 211, 22))
        self.comboes.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboes.setObjectName("comboes")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 130, 111, 21))
        self.label_3.setObjectName("label_3")
        self.boton3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton3.setGeometry(QtCore.QRect(290, 160, 101, 23))
        self.boton3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.boton3.setObjectName("boton3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.boton1.setText(_translate("MainWindow", "Importar Archivo CSV"))
        self.boton2.setText(_translate("MainWindow", "Graficar"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; color:#f0f0f0;\">Eje de las X</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; color:#f0f0f0;\">Eje de las Y</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; color:#f0f0f0;\">Estadistica</span></p></body></html>"))
        self.boton3.setText(_translate("MainWindow", "Estadistica"))
